### ISSUE TITLE
Need A Tutorial Step By Step

### ISSUE THREAD

**Issue by izumiipls** [PointFool/docker-buat-ujian-industri#1]
Butuh step by step nya di jelasin, untuk apa untuk apa nya, sekalian (issue pertama) 🙏

**Comment by PointFool** [comment]
you said "LaGiAn NgApAiN BuAt BeGiTuAn" -_-

**Comment by PointFool** [comment]
1. git clone https://github.com/PointFool/docker-buat-ujian-industri.git
2. cd docker-buat-ujian-industri/
3. sh mengetes.sh

-_-
